INDIAN_STOCKS = [
    "TCS.NS", "INFY.NS", "RELIANCE.NS", "HDFCBANK.NS",
    "WIPRO.NS", "ICICIBANK.NS", "HINDUNILVR.NS", "ITC.NS",
    "SBIN.NS", "BAJFINANCE.NS", "ADANIENT.NS", "TATAMOTORS.NS",
    "MARUTI.NS", "SUNPHARMA.NS", "TITAN.NS", "TECHM.NS",
    "HCLTECH.NS", "AXISBANK.NS", "KOTAKBANK.NS", "LT.NS",
    "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "COALINDIA.NS",
    "BPCL.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "BRITANNIA.NS"
]

US_STOCKS = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA",
    "JPM", "BAC", "WMT", "JNJ", "PG", "V", "MA", "UNH",
    "HD", "DIS", "NFLX", "PYPL", "INTC", "AMD", "CSCO",
    "PFE", "KO", "PEP", "MCD", "NKE", "SBUX", "UBER"
]

ALL_STOCKS = INDIAN_STOCKS + US_STOCKS
